main:
  - name: Home
    url: '#hero'
    weight: 10
  - name: Projects
    url: '#projects'
    weight: 20
  - name: Posts
    url: '#posts'
    weight: 30
  - name: Events
    identifier: events
    weight: 35
  - name: Upcoming Events
    url: '/#events'
    parent: events
    weight: 10
  - name: Past Events
    url: '/#past-events'
    parent: events
    weight: 20
  - name: KI Seminars (online)
    url: '/#seminar'
    parent: events
    weight: 20
  - name: People
    identifier: people
    weight: 70
  - name: Affiliated Faculty
    parent: people
    url: '#people'
  - name: Postdocs
    parent: people
    url: "/postdocs/"
  - name: Graduate Students
    parent: people
    url: '/students/'
  - name: Subscribe
    url: '#mailinglist'
    weight: 80
  - name: Sponsors
    url: '#sponsors'
    weight: 90

